# Generated by Django 4.2.11 on 2024-03-13 11:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('sizes', models.IntegerField(choices=[(0, 'Size 6'), (1, 'Size 7'), (2, 'Size 8'), (3, 'Size 9'), (4, 'Size 10'), (5, 'Size 11'), (6, 'Size 12')], default=0)),
            ],
        ),
    ]
