# Generated by Django 4.2.11 on 2024-03-20 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
